title: 
logo: img/photo2018.jpg
description: >
Cheng Chou
Email: cchou@le.ac.uk
Phone: +44 (0) 116 373 6288
Address: School of Business
University Road
University of Leicester
Leicester, UK, LE1 7RH
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
